//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.239
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MSMQNoSecurityClient.MSMQServiceReference {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="MSMQServiceReference.IMSMQService")]
    public interface IMSMQService {
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IMSMQService/ShowMessage")]
        void ShowMessage(string msg);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IMSMQServiceChannel : MSMQNoSecurityClient.MSMQServiceReference.IMSMQService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class MSMQServiceClient : System.ServiceModel.ClientBase<MSMQNoSecurityClient.MSMQServiceReference.IMSMQService>, MSMQNoSecurityClient.MSMQServiceReference.IMSMQService {
        
        public MSMQServiceClient() {
        }
        
        public MSMQServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public MSMQServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public MSMQServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public MSMQServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public void ShowMessage(string msg) {
            base.Channel.ShowMessage(msg);
        }
    }
}
