//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Client.HelloIndigoExService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="HelloIndigoExService.IHelloIndigoExService")]
    public interface IHelloIndigoExService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IHelloIndigoExService/GetMessage", ReplyAction="http://tempuri.org/IHelloIndigoExService/GetMessageResponse")]
        string GetMessage(string name);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IHelloIndigoExServiceChannel : Client.HelloIndigoExService.IHelloIndigoExService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class HelloIndigoExServiceClient : System.ServiceModel.ClientBase<Client.HelloIndigoExService.IHelloIndigoExService>, Client.HelloIndigoExService.IHelloIndigoExService {
        
        public HelloIndigoExServiceClient() {
        }
        
        public HelloIndigoExServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public HelloIndigoExServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public HelloIndigoExServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public HelloIndigoExServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string GetMessage(string name) {
            return base.Channel.GetMessage(name);
        }
    }
}
