.PHONY: clean All

All:
	@echo "----------Building project:[ HelloCpp - Release ]----------"
	@cd "HelloCpp" && "$(MAKE)" -f  "HelloCpp.mk"
clean:
	@echo "----------Cleaning project:[ HelloCpp - Release ]----------"
	@cd "HelloCpp" && "$(MAKE)" -f  "HelloCpp.mk" clean
