//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MSMQSecuredClient.SecureMSMQServiceReference {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="SecureMSMQServiceReference.ISecuredMSMQService")]
    public interface ISecuredMSMQService {
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/ISecuredMSMQService/ShowSecureMessage")]
        void ShowSecureMessage(string msg);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ISecuredMSMQServiceChannel : MSMQSecuredClient.SecureMSMQServiceReference.ISecuredMSMQService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class SecuredMSMQServiceClient : System.ServiceModel.ClientBase<MSMQSecuredClient.SecureMSMQServiceReference.ISecuredMSMQService>, MSMQSecuredClient.SecureMSMQServiceReference.ISecuredMSMQService {
        
        public SecuredMSMQServiceClient() {
        }
        
        public SecuredMSMQServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public SecuredMSMQServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SecuredMSMQServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SecuredMSMQServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public void ShowSecureMessage(string msg) {
            base.Channel.ShowSecureMessage(msg);
        }
    }
}
