#ifndef FIRSTSHAREDLIB_GLOBAL_H
#define FIRSTSHAREDLIB_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(FIRSTSHAREDLIB_LIBRARY)
#  define FIRSTSHAREDLIBSHARED_EXPORT Q_DECL_EXPORT
#else
#  define FIRSTSHAREDLIBSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // FIRSTSHAREDLIB_GLOBAL_H
